#!/usr/bin/env python3
"""
trg Application Release Black-Box Verifier
Validates:
1. Archive integrity & SHA-256 match.
2. License & file presence (LICENSE, package.tk, build.tk, src/).
3. Clean standalone archive extraction.
4. Online dependency resolution (regex:0.3.0 via default public registry).
5. Application compilation (toka build) and version identity (trg 0.3.1 (Toka)).
6. Functional verification of literal and regex search (-F, -E, -w, -x, -C, --json).
7. Offline replay (TOKA_OFFLINE=1) after purging unpacked packages.
"""

import argparse
import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

def log(msg):
    print(f"[APP-VERIFY] {msg}", flush=True)

def compute_sha256(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()

def run_cmd(cmd, cwd=None, env=None, unset_env=None, check=True):
    merged_env = os.environ.copy()
    if unset_env:
        for k in unset_env:
            merged_env.pop(k, None)
    if env:
        merged_env.update(env)
    res = subprocess.run(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=merged_env
    )
    if check and res.returncode != 0:
        raise RuntimeError(f"Command failed (exit {res.returncode}): {' '.join(str(x) for x in cmd)}\nSTDOUT:\n{res.stdout}\nSTDERR:\n{res.stderr}")
    return res

def verify_archive(archive_path: pathlib.Path, expected_sha: str = None) -> dict:
    actual_sha = compute_sha256(archive_path)
    if expected_sha and actual_sha.lower() != expected_sha.lower():
        raise ValueError(f"SHA-256 mismatch: expected {expected_sha}, got {actual_sha}")
    
    with tarfile.open(archive_path, "r:gz") as tar:
        names = tar.getnames()
        for member in tar.getmembers():
            if member.issym() or member.islnk():
                raise ValueError(f"Security violation: archive contains link entry '{member.name}' -> '{member.linkname}'")
            if member.isdev() or member.ischr() or member.isblk() or member.isfifo():
                raise ValueError(f"Security violation: archive contains special device/fifo entry '{member.name}'")
            if member.name.startswith("/") or ".." in member.name:
                raise ValueError(f"Security violation: path escape in archive entry '{member.name}'")
            if member.name.endswith((".o", ".a", ".dylib", ".so")):
                raise ValueError(f"Security violation: precompiled binary found '{member.name}'")
            if ".git" in member.name.split("/"):
                raise ValueError(f"Security violation: .git metadata in archive entry '{member.name}'")
        
        # Check mandatory files
        root_entries = {n.split("/")[0] for n in names}
        has_license = any(n.lower() in ("license", "license.txt", "license.md") or n.lower().endswith("/license") for n in names)
        has_package = any(n == "package.tk" or n.endswith("/package.tk") for n in names)
        has_build = any(n == "build.tk" or n.endswith("/build.tk") for n in names)
        
        if not has_license:
            raise ValueError("Mandatory Apache-2.0 LICENSE file missing from archive!")
        if not has_package:
            raise ValueError("package.tk missing from archive!")
        if not has_build:
            raise ValueError("build.tk missing from archive!")

    return {
        "archive_sha256": actual_sha,
        "entry_count": len(names),
        "license_verified": True
    }

def verify_extracted_build(extracted_root: pathlib.Path, toka_bin: str) -> dict:
    # 1. toka doctor and check
    r_doc = run_cmd([toka_bin, "doctor"], cwd=extracted_root, unset_env=["TOKA_REGISTRY_URL", "TOKA_OFFLINE"])
    r_chk = run_cmd([toka_bin, "check", "--json", "package.tk"], cwd=extracted_root, unset_env=["TOKA_REGISTRY_URL", "TOKA_OFFLINE"])
    chk_json = json.loads(r_chk.stdout)
    if not chk_json.get("success"):
        raise RuntimeError(f"toka check failed: {r_chk.stdout}")

    # 2. Online fetch via public registry
    log("Running online toka fetch against default registry...")
    r_fetch = run_cmd([toka_bin, "fetch"], cwd=extracted_root, unset_env=["TOKA_REGISTRY_URL", "TOKA_OFFLINE"])
    
    lock_file = extracted_root / "package.lock"
    if not lock_file.exists():
        raise RuntimeError("package.lock was not generated by toka fetch")
    lock_content = lock_file.read_text(encoding="utf-8")
    if "regex" not in lock_content or "0.3.0" not in lock_content:
        raise RuntimeError(f"package.lock does not record regex 0.3.0: {lock_content}")

    # 3. toka build
    log("Compiling application with toka build...")
    r_build = run_cmd([toka_bin, "build"], cwd=extracted_root, unset_env=["TOKA_REGISTRY_URL", "TOKA_OFFLINE"])
    
    app_bin = extracted_root / "target" / "debug" / "trg"
    if not app_bin.exists():
        raise RuntimeError(f"Built binary {app_bin} does not exist")

    # 4. Assert Version
    r_ver = run_cmd([str(app_bin), "--version"])
    version_out = r_ver.stdout.strip()
    if version_out != "trg 0.10.0 (Toka)":
        raise RuntimeError(f"Unexpected version output: {version_out}")

    # 5. Functional Sanity
    log("Running functional sanity checks...")
    # Literal search
    r_lit = run_cmd([str(app_bin), "-F", "trg", "package.tk"], cwd=extracted_root)
    if "name = \"trg\"" not in r_lit.stdout:
        raise RuntimeError(f"Literal search failed: {r_lit.stdout}")

    # Regex word search
    r_re_w = run_cmd([str(app_bin), "-E", "-w", "pub|const", "package.tk"], cwd=extracted_root)
    if "pub const PACKAGE" not in r_re_w.stdout:
        raise RuntimeError(f"Regex word search failed: {r_re_w.stdout}")

    # Regex context search
    r_ctx = run_cmd([str(app_bin), "-n", "-C", "1", "name = \"trg\"", "package.tk"], cwd=extracted_root)
    if "1-pub const PACKAGE" not in r_ctx.stdout or "3-    version =" not in r_ctx.stdout:
        raise RuntimeError(f"Context search failed: {r_ctx.stdout}")

    # JSON streaming schema
    r_json = run_cmd([str(app_bin), "--json", "-E", "version\\s+=", "package.tk"], cwd=extracted_root)
    lines = [json.loads(line) for line in r_json.stdout.strip().split("\n") if line]
    if lines[0].get("type") != "begin" or lines[0].get("schema") != "trg-json-v2":
        raise RuntimeError(f"Invalid JSON framing: {r_json.stdout}")

    # 6. Offline replay test
    log("Testing offline build replay...")
    shutil.rmtree(extracted_root / ".toka" / "packages", ignore_errors=True)
    env_offline = {
        "TOKA_REGISTRY_URL": "http://127.0.0.1:9",
        "TOKA_OFFLINE": "1"
    }
    
    r_off_fetch = run_cmd([toka_bin, "fetch"], cwd=extracted_root, env=env_offline)
    r_off_build = run_cmd([toka_bin, "build"], cwd=extracted_root, env=env_offline)
    
    r_off_ver = run_cmd([str(app_bin), "-V"])
    if r_off_ver.stdout.strip() != "trg 0.10.0 (Toka)":
        raise RuntimeError("Offline binary failed version check")

    return {
        "online_build": "PASS",
        "version_check": version_out,
        "functional_sanity": "PASS",
        "offline_replay": "PASS"
    }

def main():
    parser = argparse.ArgumentParser(description="Verify trg application release package")
    parser.add_argument("--archive", type=pathlib.Path, help="Path to local trg archive")
    parser.add_argument("--url", type=str, help="URL to download release archive from")
    parser.add_argument("--sha256", type=str, help="Expected archive SHA-256")
    parser.add_argument("--toka", type=str, default="toka", help="Path to toka binary")
    args = parser.parse_args()

    toka_bin = shutil.which(args.toka) or args.toka
    if not os.path.exists(toka_bin):
        candidate_sdks = [
            "/Users/zhyi/.toka-sdks/1.0.0-rc.11/bin/toka",
            str(pathlib.Path.home() / ".toka-sdks" / "1.0.0-rc.11" / "bin" / "toka"),
        ]
        for c in candidate_sdks:
            if os.path.exists(c):
                toka_bin = c
                break

    with tempfile.TemporaryDirectory(prefix="trg-verify-") as tmp_dir:
        tmp = pathlib.Path(tmp_dir)
        archive_file = tmp / "trg.tar.gz"

        if args.url:
            log(f"Downloading release archive from: {args.url}")
            urllib.request.urlretrieve(args.url, archive_file)
        elif args.archive:
            shutil.copy(args.archive, archive_file)
        else:
            raise ValueError("Either --archive or --url must be specified")

        log(f"Verifying archive: {archive_file}")
        archive_meta = verify_archive(archive_file, expected_sha=args.sha256)
        log(f"Archive SHA-256: {archive_meta['archive_sha256']} (contains LICENSE: {archive_meta['license_verified']})")

        extract_dir = tmp / "extracted"
        extract_dir.mkdir()
        with tarfile.open(archive_file, "r:gz") as tar:
            tar.extractall(extract_dir)

        # Find package root inside extracted folder
        if (extract_dir / "package.tk").exists():
            pkg_root = extract_dir
        else:
            children = list(extract_dir.iterdir())
            if len(children) == 1 and children[0].is_dir():
                pkg_root = children[0]
            else:
                pkg_root = extract_dir

        log(f"Extracted package root: {pkg_root}")
        build_meta = verify_extracted_build(pkg_root, toka_bin)

        report = {
            "schema": "toka.trg-application-verification-v1",
            "version": "0.10.0",
            "result": "PASS",
            "archive": archive_meta,
            "verification": build_meta
        }
        print(json.dumps(report, indent=2))
        log("ALL APPLICATION RELEASE CRITERIA PASSED!")

if __name__ == "__main__":
    main()
